server:
 port: 8888
 ssl: 
  key-store: classpath:5043955_erfengv.com.pfx
  key-store-type: PKCS12
  key-store-password: yRgq3mAf
  

#配置数据源 
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/db_qq?serverTimezone=UTC&CharacterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: 111
  driver-class-name: com.mysql.cj.jdbc.Driver
 
#日志配置
logging:
 level:
  com.example.BlogPErfeng.dao: debug