server:
 port: 80

#配置数据源
spring:
 datasource:
  url: jdbc:mysql://123.57.20.138:3306/db_qq?serverTimezone=UTC&CharacterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: wgf123lxl
  driver-class-name: com.mysql.cj.jdbc.Driver
 
#日志配置
logging:
 level:
  com.example.BlogPErfeng.dao: debug